### ISSUE TITLE
[BUG]튕김

### ISSUE THREAD

**Issue by hitomiraita** [tom5079/Pupil-issue#1]
**버그 설명**
어떤 버그인지 명확하게 설명해주세요
작품보려고 누르면 튕김
**버그를 확인하는 방법**
버그를 다시 일으키기 위한 방법을 상세하게 써주세요
이하동문
**어떻게 고쳐야 할까요?**
버그를 고칠 방법은 여러개 있을 수 있습니다.
그 중 하나를 제안해 주세요!

**스크린샷**
스크린샷도 첨부해 주시면 더욱 빠르게 버그를 고칠 수 있습니다!

**기종/환경**
 - 기종: [예) 갤럭시 S8+]
 - OS: [예) 안드로이드 오레오]
 - 앱 버전: [예) 1.1]
홍미노트7 앱버전 2.1
**추가설명**
더 전달하고 싶은 것이 있으면 여기에 적어주세요!

**Comment by tom5079** [comment]
현재 통신사 HTTPS 검열이 시작되었더군요.
히토미는 안 막는데서 못 받아오면 오류를 뿜게 했는데 이렇게 금방 막힐 줄이야...
일단 우회하면 정상 접속되는 것 확인했습니다.
상세는 [깃헙 페이지](https://tom5079.github.io/Pupil/2019/05/30/https-block-kr.html) 참조하시기 바랍니다.

늦은 답변 죄송합니다.
