### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by nodey755** [tom5079/Pupil-issue#2]
**이 기능이 해결될 수 있는 문제**
이 기능이 추가되어 해결될 수 있는 문제를 적어주세요!

**기능 상세 설명**
추가되었으면 하는 기능을 상세하게 설명해 주세요!

**다른 방법이 있을까요?**
다른 방법으로 문제를 해결할 수 있는 방법이 있다면, 그것도 적어주세요!

**추가 설명**
더 전달하고 싶은 것이 있으면 여기에 적어주세요!

**Comment by tom5079** [comment]
??
