### ISSUE TITLE
[FR] 코드 검색기능 다시넣어주실수 있나요

### ISSUE THREAD

**Issue by wodyd971** [tom5079/Pupil-issue#3]
**이 기능이 해결될 수 있는 문제**
검색의 편리성?

**기능 상세 설명**
히토미코드로 갤러리를 검색할수 있는 기능

**다른 방법이 있을까요?**
다른 방법으로 문제를 해결할 수 있는 방법이 있다면, 그것도 적어주세요!

**추가 설명**
분명히 설명서에는 코드검색기능이 있는데 제 화면에선 나오지 않네요, 저만그런지 모르겠어서 이렇게 질문드립니다

**Comment by tom5079** [comment]
위로 올리시면 + 버튼 나와용
거기에 갤러리 번호로 열기 쓰시면 됩니다
설명서도 업데이트 했어요
